// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://igvqzwsezjcrzizdfatx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlndnF6d3NlempjcnppemRmYXR4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg2OTA2MDUsImV4cCI6MjA3NDI2NjYwNX0.Cac9okkqjcLMoVRnrbXtUwMNshEkbasB1pv7Yk0X0Qg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});